### ISSUE TITLE
Checking "Content-Type" header value for 'application/vnd.api+json'

### ISSUE THREAD

**Issue by mitchlloyd** [orbitjs/orbit-jsonapi#3]
This library is checking that the `Content-Type` response header is `===` to `application/vnd.api+json`, however it is valid and common to include additional content in this header. For instance, Rails and Phoenix servers will send `"application/vnd.api+json; charset=utf-8`. 

https://github.com/orbitjs/orbit-jsonapi/blob/fe80c293d66ac130e6bb5a7b16f53543b7edf426/src/jsonapi-source.js#L173

Also tracking down this error was challenging because this issue results in the `deserialize` method receiving `undefined` as it's `data`. Perhaps there could be an earlier assertion explaining that the `Content-Type` header was not correct?

**Comment by dgeb** [comment]
Sorry for the trouble. I agree the current restriction is too harsh. At the very least, we should be checking for the _presence_ of this string as opposed to strict equality.

I think it would be best to also align status codes with the expectations of content. For instance, a `201` should throw a `ContentExpected` error if none is provided and a `204` should throw an `UnexpectedContent` error is content is provided (or similar - suggestions welcome).

**Comment by dgeb** [comment]
Working on this. Maybe `ServerResponseContentExpected` is the only error needed. I'm not sure that unexpected content should result in an error. Some servers might sloppily set `Content-Type` even when there's no document, and I think we can be forgiving in those situations.
