### ISSUE TITLE
Not possible to query with queryParams

### ISSUE THREAD

**Issue by mitchlloyd** [orbitjs/orbit-jsonapi#7]
Looking at [the calls to fetch](https://github.com/orbitjs/orbit-jsonapi/blob/c8725cf1300ada908a5255c7c9e2a3b706ca1929/src/lib/queries.js#L23-L59) it seems like there is only one query param allowed (`filter`) for a `records` query.

I think this should be opened up to allow additional query params for each type of query. For instance, this is important for supporting the [JSONAPI `include` param](http://jsonapi.org/format/#fetching-includes).

**Comment by jpvanhal** [comment]
@dgeb, do you have any ideas regarding the `include` param? This is one of the few issues that are still preventing us from upgrading to 0.8. 

Some ideas for the possible query syntax:

``` js
// OQE
oqe('records', 'planet', { include: ['star', 'moons'] })

// QB
qb.records('planet', { include: ['star', 'moons'] })
```

``` js
// OQE
oqe('include', 
  oqe('records', 'planet'),
  ['star', 'moons'])

// QB
qb.records('planet')
  .include('star', 'moons')
```

**Comment by dgeb** [comment]
Refinements like `page`, `sort`, and `filter` can be both applied to every source and affect the results of the query in a predictable way. Therefore, it makes a lot of sense for them to be first-order query expressions.

However, I think options like `include` are a bit different. They don't apply to sources in the same way - a Store may safely ignore `include` while still allowing it to be passed through to a JSONAPISource. Essentially, I think we need a way to refine queries _for specific sources_ by passing optional instructions for those sources. These options could be used for query params, headers, etc. that only make sense for particular sources.

The way I've been planning to handle this is through the `options` hash that can be passed into `Query` and `Transform` constructors. We could reserve a top-level `sources` key in this hash, which could be further broken down by source name.

So an `include` param could be passed into a query constructed on the store, and then flow through to the JSONAPISource's `pull` method. For example:

```
store.query(qb.records('planet'), { sources: { jsonapi: { include: ['star', 'moons'] }}});
```

In this way, the options don't become part of the query expression, but just get embedded in the Query instance.

@mitchlloyd @jpvanhal Please let me know what you guys think of this approach.

**Comment by jpvanhal** [comment]
I think that makes a lot of sense. I'll flesh out some PRs to get this forward.

**Comment by dgeb** [comment]
Great - thanks @jpvanhal 👍

**Comment by dgeb** [comment]
Thanks to @jpvanhal's implementation of my suggestion, it's now possible to pass source-specific settings to queries 👍 

The JSONAPISource currently supports `filter`, `include`, `page`, and `sort` params, but the solution is generalized and allows for others to be added in the future.
